package io.plugin.assets;

import org.bukkit.plugin.java.JavaPlugin;

public class Main extends JavaPlugin {
    @Override
    public void onEnable() {
    }
  
    @Override
    public void onDisable() {
        Number count = 0;
    }
}
//Autogenerated by KoalaPlugin
//This file is part of KoalaPlugin, a plugin generator for Bukkit plugins.