name: PluginName # Name of the plugin
version: 1.0.0
main: com.plugin.assets.Main # Main class of the plugin
# depend: [SomeDependency ex. WorldEdit, LuckPerms, PlaceholderAPI, ] # List of dependencies if any 
api-version: 1.21 # Minecraft API version
author: YourName # Author of the plugin
description: (description here) # A brief description of what the plugin does
commands: []


